### ISSUE TITLE
Add libssh library

### ISSUE THREAD

**Issue by lethean** [nvrsw/gtk-win32#1]

**Comment by lethean** [comment]
> libssh의 경우 빌드하는 방법은 알아냈습니다. 그런데 msvc프로젝트를 생성한뒤 빌드하는 방식이라서 gtk-win32에 어떻게 넣어야 할지 고민하고 있습니다. 그리고 libssh2도 확인해 보겠습니다..

libssh2 라이브러리는 확인하지 않아도 됩니다.

CMake가 MSVC 프로젝트를 생성하는 방식이라면 스크립트에서 순서대로 호출해주면 되는거 아닌가요?

**Comment by hsccr** [comment]
libssh를 추가해서 커밋했습니다.
